version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: mlops-backend
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - AWS_BEARER_TOKEN_BEDROCK=${AWS_BEARER_TOKEN_BEDROCK}
    ports:
      - "8001:8000"
    depends_on:
      - mlflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.6.0
    container_name: mlops-mlflow
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlruns
      --host 0.0.0.0
      --port 5000
      --allowed-hosts "mlflow:5000,localhost:5001,127.0.0.1:5001"
    ports:
      - "5001:5000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: mlops-frontend
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "8502:8501"
    depends_on:
      - backend
